### ISSUE TITLE
Paths not working, when running PW from subdirectory

### ISSUE THREAD

**Issue by apeisa** [jdart/Spex#7]
Hi - taking a closer look of Spex today and I run my dev sites from subdir. I noticed problem with paths. Let say my site runs on www.domain.com/mysite/. In my template file I have:
$spex->addStyle('styles/main.less');

and in /layouts/_base.php
<?= $spex->includeStyles(); ?>

But this ends up in error:
fatal error: load error: failed to find /var/www/mysite/mysite/site/templates/styles/main.less

So it duplicates the subsite directory. Problem lies in this method:
https://github.com/jdart/Spex/blob/master/Spex.module#L285

**Comment by jdart** [comment]
Can I get you to pull changes from master, I've added a change that should fix your issue.

**Comment by jdart** [comment]
I'm going to assume this is resolved.
