### ISSUE TITLE
jquery loading in backend

### ISSUE THREAD

**Issue by geniestreiche** [jdart/Spex#8]
When the module is in a directory other than Spex, there is an page not found error for the jquery library in the backend. Maybe it is not necessary to load jquery in the backend.

**Comment by jdart** [comment]
Hi geniestreiche, I pushed a change that will prevent spex from adding its own jquery in the backend. Let me know if that does the trick for you.

https://github.com/jdart/Spex/commit/25ca3d428d00203456b4cb769df34f9a8ee5d4db

**Comment by geniestreiche** [comment]
Thanks jdart, i think it works but now i have another problem: i no longer see the spex module in the module list...

**Comment by jdart** [comment]
I think that's a bug in PW, I've opened an issue on the PW project. In the meantime if you checkout 25ca3d428d00203456b4cb769df34f9a8ee5d4db you should be ok.

git checkout 25ca3d428d00203456b4cb769df34f9a8ee5d4db .

The issue: https://github.com/ryancramerdesign/ProcessWire/issues/375

**Comment by jdart** [comment]
Ryan mentioned the bug has been fixed in the dev branch, so you can either stick with the spex revision I mentioned above, or you can use the dev branch of pw. Thanks for the bug report!
